defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      lang: en
      base-url: "/"
  - scope:
      path: de
    values:
      lang: de
      base-url: "/de/"

url: "https://fabianbissmann.de"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-feed

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    css_class: 'highlight'
    #span:
    #  line_numbers: false
    #block:
    #  line_numbers: true
    #  start_line: 1

sass:
  style: compact

title: "Fabian Bißmann"
description: "A journal focusing on IT specific topics."
url: "fabianbissmann.de"
author: "Fabian Bißmann"
